mysql:
  enabled: false

postgresql:
  enabled: false

catalog:
  app:
    persistence:
      provider: mysql
      endpoint: "${catalog_db_endpoint}:${catalog_db_port}"
      database: "catalog"
      secret:
        create: false
        name: "catalog-db"
        username: "catalog"
  mysql:
    create: false

orders:
  app:
    persistence:
      provider: postgres
      endpoint: "${orders_db_endpoint}:${orders_db_port}"
      database: "orders"
      secret:
        create: false
        name: "orders-db"
        username: "orders"
  postgresql:
    create: false

redis:
  enabled: true

rabbitmq:
  enabled: true

dynamodb:
  enabled: true

dynamodbLocal:
  enabled: true
